sensors:
  - camera_pointcloud

camera_pointcloud:
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /points_world
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.0
    padding_scale: 1.0
    max_update_rate: 1.0
    self_mask: false
    filtered_cloud_topic: ""